#!/usr/bin/env python3
"""
scripts/compress_esmfold2_metadata.py — Stage 2b
===================================================
Adapted from ab_initio_pipeline's scripts/compress_abcfold_metadata.py for a
single backend (ESMFold2-Fast, one seed, N diffusion samples per pair)
instead of ABCfold's 6-backend x many-seed sprawl. Converts
results/<pair>/raw/sample_<i>.cif + sample_<i>_confidences.json into two
compact artifacts per pair:

  results/metadata/<pair>/
    model_metadata.parquet   - one row per sample_index: ptm, iptm,
                                mean_plddt, cif_path, array_key, extra_json
                                (pair_chains_iptm/chain topology/residue
                                index -- everything EXCEPT the pae/plddt
                                arrays, which stay in arrays.h5 only, never
                                duplicated). zstd-compressed.
    arrays.h5                - pae / plddt per sample, float16, gzip+shuffle
                                compressed, keyed by sample_index; chain
                                topology (chain_id per token, chain_lookup)
                                written once per pair under _topology/<pair>/
                                since it's identical across every sample.
  results/metadata/all_models.parquet
                            - concat of every pair's model_metadata.parquet

Precision: pae is capped in [0, ~31.75) and already bucketed at inference
time, plddt is a [0,1] confidence -- float16 keeps ample resolution for
both, matching ab_initio_pipeline's own precision rationale.

Safety: default mode is WRITE-ONLY (the raw results/<pair>/raw/ tree is left
untouched). Every write is verified (row count, a handful of decoded
float16 values compared back against source) before being considered clean.
Pass --delete-originals to also remove, ONLY for pairs whose verification
passed, the raw per-sample JSON files just replaced (the CIFs themselves are
kept -- they are the only copy of the structure, unlike ABCfold's redundant
per-backend caches).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import h5py
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from parquet_utils import write_parquet_with_metadata  # noqa: E402

MODEL_METADATA_TABLE_DESCRIPTION = (
    "Standardized per-sample scalar confidence metadata for one nanopulldown "
    "bait/prey pair (one seed, N ESMFold2-Fast diffusion samples), replacing "
    "the raw per-sample confidence JSON sprawl under results/<pair>/raw/ (see "
    "this script's module docstring). One row per diffusion sample. The full "
    "pae/plddt arrays for a row live in this pair's sibling arrays.h5, keyed "
    "by this row's array_key. Generated by scripts/compress_esmfold2_metadata.py."
)
MODEL_METADATA_COLUMN_DESCRIPTIONS = {
    "pair": "Bait__prey pair identifier (configs/<pair>.yaml stem)",
    "seed": "Random seed used for this pair's ESMFold2-Fast run",
    "sample_index": "Diffusion sample index within that seed (0-based)",
    "frame_id": "Human-readable identifier combining pair/seed/sample_index",
    "cif_path": "Path to this sample's structure file, relative to --results-root",
    "array_key": "This sample's group key under the pair's arrays.h5 (holds "
                 "pae/plddt when has_array is True)",
    "extra_json": "ESMFold2's per-sample confidences payload as JSON text, "
                  "MINUS pae/plddt (those live in the sibling arrays.h5 as "
                  "float16 -- duplicating O(N^2)/O(N) float arrays here as "
                  "JSON text would defeat the point of compression). Keeps "
                  "seed, ptm, iptm, pair_chains_iptm, chain_id, "
                  "chain_lookup, residue_index.",
    "has_array": "True if pae/plddt for this sample were written to the "
                 "sibling arrays.h5",
    "ptm": "Predicted TM-score (pTM) reported by ESMFold2 for this sample",
    "iptm": "Predicted interface TM-score (ipTM) for this sample",
    "mean_plddt": "Mean per-token pLDDT (0-1 scale, as ESMFold2 reports it) "
                  "for this sample",
}


def discover_samples(raw_dir: Path) -> list[int]:
    indices = []
    for cif in sorted(raw_dir.glob("sample_*.cif")):
        try:
            indices.append(int(cif.stem.split("_")[1]))
        except (IndexError, ValueError):
            continue
    return sorted(indices)


def process_pair(pair: str, results_root: Path, out_root: Path) -> dict:
    raw_dir = results_root / pair / "raw"
    indices = discover_samples(raw_dir)
    if not indices:
        raise FileNotFoundError(f"No sample CIFs found for {pair} under {raw_dir}")

    out_dir = out_root / pair
    out_dir.mkdir(parents=True, exist_ok=True)
    h5_path = out_dir / "arrays.h5"
    parquet_path = out_dir / "model_metadata.parquet"

    rows = []
    bytes_before = 0
    array_datasets = 0
    topology_written = False

    with h5py.File(h5_path, "w") as h5f:
        for idx in indices:
            cif_path = raw_dir / f"sample_{idx}.cif"
            json_path = raw_dir / f"sample_{idx}_confidences.json"
            payload = json.loads(json_path.read_text()) if json_path.exists() else {}
            bytes_before += json_path.stat().st_size if json_path.exists() else 0

            array_key = f"sample_{idx}"
            has_array = False
            if payload.get("pae") is not None:
                h5f.create_dataset(f"{array_key}/pae",
                                    data=np.asarray(payload["pae"], dtype=np.float16),
                                    compression="gzip", compression_opts=4, shuffle=True)
                array_datasets += 1
                has_array = True
            if payload.get("plddt") is not None:
                h5f.create_dataset(f"{array_key}/plddt",
                                    data=np.asarray(payload["plddt"], dtype=np.float16),
                                    compression="gzip", compression_opts=4, shuffle=True)
                array_datasets += 1
                has_array = True
            if not topology_written and payload.get("chain_id") is not None:
                ds = h5f.create_dataset(f"_topology/{pair}/chain_id",
                                         data=np.asarray(payload["chain_id"], dtype=np.int32),
                                         compression="gzip", compression_opts=4)
                ds.attrs["chain_lookup"] = json.dumps(payload.get("chain_lookup") or {})
                topology_written = True

            plddt = payload.get("plddt")
            mean_plddt = float(np.mean(plddt)) if plddt else None

            # extra_json is the lossless-but-SMALL sidecar: pae/plddt are
            # O(N^2)/O(N) float arrays already written to arrays.h5 above --
            # duplicating them here as JSON text would defeat the entire
            # point of "metadata compression" (JSON floats compress far
            # worse than binary float16). Keep only the scalar/topology
            # fields compute_interface_metrics.py and plot_domain_heatmap.py
            # actually read from this column: residue_index and chain_id are
            # O(N) ints (cheap even uncompressed), pair_chains_iptm is a
            # small chain x chain matrix.
            extra = {k: v for k, v in payload.items() if k not in ("pae", "plddt")}

            rows.append({
                "pair": pair, "seed": payload.get("seed"), "sample_index": idx,
                "frame_id": f"{pair}_seed{payload.get('seed')}_sample{idx}",
                "cif_path": cif_path.relative_to(results_root).as_posix(),
                "array_key": array_key,
                "extra_json": json.dumps(extra),
                "has_array": has_array,
                "ptm": payload.get("ptm"),
                "iptm": payload.get("iptm"),
                "mean_plddt": mean_plddt,
            })

    df = pd.DataFrame(rows)
    for col in ("ptm", "iptm", "mean_plddt"):
        df[col] = df[col].astype("float32")
    write_parquet_with_metadata(
        df, parquet_path,
        table_description=MODEL_METADATA_TABLE_DESCRIPTION,
        column_descriptions=MODEL_METADATA_COLUMN_DESCRIPTIONS,
    )

    return {
        "pair": pair, "n_rows": len(df), "n_arrays": array_datasets,
        "bytes_before": bytes_before,
        "h5_bytes": h5_path.stat().st_size,
        "parquet_bytes": parquet_path.stat().st_size,
    }


def verify_pair(pair: str, results_root: Path, out_root: Path, sample_checks: int) -> list[str]:
    problems = []
    raw_dir = results_root / pair / "raw"
    out_dir = out_root / pair
    parquet_path = out_dir / "model_metadata.parquet"
    h5_path = out_dir / "arrays.h5"

    indices = discover_samples(raw_dir)
    df = pd.read_parquet(parquet_path)
    if len(df) != len(indices):
        problems.append(f"row count {len(df)} != {len(indices)} CIFs discovered under {raw_dir}")

    has_array_rows = df[df["has_array"]]
    if len(has_array_rows) == 0:
        return problems

    n = min(sample_checks, len(has_array_rows))
    sample = has_array_rows.sample(n=n, random_state=0)

    with h5py.File(h5_path, "r") as h5f:
        for _, row in sample.iterrows():
            key = row["array_key"]
            json_path = raw_dir / f"sample_{row['sample_index']}_confidences.json"
            if not json_path.exists():
                problems.append(f"{key}: source confidences json no longer available to verify against")
                continue
            payload = json.loads(json_path.read_text())
            if payload.get("pae") is not None:
                if f"{key}/pae" not in h5f:
                    problems.append(f"{key}: missing pae dataset in arrays.h5")
                    continue
                h5_pae = h5f[f"{key}/pae"][()]
                src_pae = np.asarray(payload["pae"], dtype=np.float32)
                if h5_pae.shape != src_pae.shape:
                    problems.append(f"{key}: pae shape mismatch {h5_pae.shape} vs source {src_pae.shape}")
                elif not np.allclose(h5_pae.astype(np.float32), src_pae, atol=0.05):
                    problems.append(f"{key}: pae values diverge beyond float16 tolerance vs source")
    return problems


def delete_originals(pair: str, results_root: Path) -> int:
    raw_dir = results_root / pair / "raw"
    freed = 0
    for p in raw_dir.glob("sample_*_confidences.json"):
        freed += p.stat().st_size
        p.unlink()
    return freed


ALL_MODELS_TABLE_DESCRIPTION = (
    "Concatenation of every pair's model_metadata.parquet -- one row per "
    "diffusion sample across every screened bait/prey pair. See "
    "MODEL_METADATA_TABLE_DESCRIPTION / each pair's own model_metadata.parquet "
    "for column meaning; see results/metadata/<pair>/arrays.h5 for the full "
    "pae/plddt arrays a row's array_key points to."
)


def merge_all(out_root: Path) -> Path | None:
    parts = sorted(out_root.glob("*/model_metadata.parquet"))
    if not parts:
        return None
    df = pd.concat((pd.read_parquet(p) for p in parts), ignore_index=True)
    out_path = out_root / "all_models.parquet"
    write_parquet_with_metadata(
        df, out_path,
        table_description=ALL_MODELS_TABLE_DESCRIPTION,
        column_descriptions=MODEL_METADATA_COLUMN_DESCRIPTIONS,
    )
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pair", required=True)
    ap.add_argument("--results-root", default="results")
    ap.add_argument("--out-root", default="results/metadata")
    ap.add_argument("--sample-checks", type=int, default=5)
    ap.add_argument("--delete-originals", action="store_true")
    ap.add_argument("--skip-merge", action="store_true")
    args = ap.parse_args()

    results_root = Path(args.results_root)
    out_root = Path(args.out_root)

    stats = process_pair(args.pair, results_root, out_root)
    problems = verify_pair(args.pair, results_root, out_root, args.sample_checks)
    if problems:
        print(f"  FAILED (verification): {len(problems)} problem(s)")
        for msg in problems[:10]:
            print(f"    - {msg}")
        return 1

    after = stats["h5_bytes"] + stats["parquet_bytes"]
    print(f"[compress] {args.pair}: {stats['n_rows']} samples, {stats['n_arrays']} arrays -> "
          f"{stats['bytes_before'] / 1e6:.2f}MB raw -> {after / 1e6:.2f}MB "
          f"(h5={stats['h5_bytes'] / 1e6:.2f}MB, parquet={stats['parquet_bytes'] / 1e6:.3f}MB), "
          f"verified clean ({args.sample_checks} spot-checks)")

    if args.delete_originals:
        freed = delete_originals(args.pair, results_root)
        print(f"[compress] deleted originals: {freed / 1e6:.2f}MB freed")

    if not args.skip_merge:
        merged = merge_all(out_root)
        if merged:
            print(f"[compress] merged metadata: {merged} ({merged.stat().st_size / 1e6:.2f}MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
